# Generated by Django 4.2.19 on 2025-04-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpersonaldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpersonaldetails',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
