# Generated by Django 4.2.19 on 2025-04-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feature', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Featuresdata',
        ),
    ]
