# Generated by Django 4.2.19 on 2025-04-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(max_length=50)),
                ('header1_des', models.CharField(max_length=300)),
                ('header2', models.CharField(max_length=50)),
                ('header2_des', models.CharField(max_length=300)),
                ('header3', models.CharField(max_length=50)),
                ('header3_des1', models.CharField(max_length=100)),
                ('header3_des2', models.CharField(max_length=100)),
                ('header3_des3', models.CharField(max_length=100)),
                ('header3_des4', models.CharField(max_length=100)),
                ('header4', models.CharField(max_length=40)),
                ('header4_des', models.CharField(max_length=300)),
                ('header5', models.CharField(max_length=40)),
                ('header5_des', models.CharField(max_length=500)),
            ],
        ),
    ]
