# Generated by Django 4.2.19 on 2025-02-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheakinDate', models.DateField()),
                ('CheakoutDate', models.DateField()),
                ('guest', models.CharField(max_length=1)),
            ],
        ),
    ]
